---

- block:
    # Manage SD + USB (mixed mode, the only available on pi4)
    # Remove rootfs partition from SD
    - block:
      - name: Find device
        shell: |
          mount -v | grep 'on {{ raspian_sd_boot_mount_dir }} ' | cut -d' ' -f1
        register: sd_boot_partition

      - debug:
          var: sd_boot_partition

      - name: 'device sd info'
        parted:
          device: '{{ sd_boot_partition.stdout[:-1] }}'
          unit: '{{ raspian_parted_unit }}'
        register: device_sd_info

      - block:

        #
        # Be fool proof when altering partitions
        # Ensure boot partition is realy on a SD card

        - name: 'is this device a SD card storage device'
          shell: |
            readlink /sys/block/{{ device_sd_info.disk.dev | regex_replace('/dev/','') }}
          register: device_sd_block
        - name: 'device SD block info debug'
          debug:
            var: device_sd_block
        - fail:
            msg: 'Not a SD card storage device : {{ device_sd_info.disk.dev }} {{ device_sd_block.stdout }}'
          when: 'not "/mmc" in device_sd_block.stdout'

        - name: 'Unmount Root partition from SD'
          # Module mount does not unmount from device path
          shell: |
            umount '{{ device_sd_info.disk.dev }}{{ device_sd_info.partitions[1].num }}'

        - name: Remove Root partition from SD if used with usb root
          parted:
            device: '{{ device_sd_info.disk.dev }}'
            number: '{{ device_sd_info.partitions[1].num }}'
            state: absent
        when: device_sd_info.partitions | length > 1

      when: raspian_usb_root_device is defined and raspian_usb_root_device

  when: raspian_sd_boot_mount_dir is defined
