---

- block:
    # add ssh (on demand)
    - name: Enable ssh
      copy:
        content: ''
        dest: '{{ boot_dir }}/ssh'
        force: no
        mode: 0740
      when: raspian_enable_ssh

    # enable wifi (on demand)
    - name: Add wifi configuration
      template:
        dest: '{{ boot_dir }}/wpa_supplicant.conf'
        src: wpa_supplicant.conf.j2
        mode: 0740
      when: raspian_enable_wifi and raspian_wifi_ssid is defined and raspian_wifi_psk is defined

    # Manage SD + USB (mixde mode, the only available on pi4)
    # Be sure we wait for root partition
    # Do not try to resize partition on the SD card
    - name: Change root partition id
      replace:
        # backup: true
        path: '{{ boot_dir }}/cmdline.txt'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.replace }}'
      with_items:
        - regexp: '^((?!.+rootwait).+)$'
          replace: '\g<1> rootwait'
        - regexp: '^(.*\s)?init=/usr/lib/raspi-config/init_resize.sh(.*)'
          replace: '\g<1>\g<2>'

  when: boot_dir is defined
