---

- block:

  - name: 'device info'
    parted:
       device: '{{ raspian_usb_root_device }}'
       unit: '{{ raspian_parted_unit }}'
    register: device_usb_info
  - debug:
      var: device_usb_info

  - name: 'is this device a USB storage device'
    shell: |
      readlink /sys/block/{{ device_usb_info.disk.dev | regex_replace('/dev/','') }}
    register: device_usb_block
  - debug:
    var: device_usb_block
  - fail:
      msg: 'Not a USB storage device : {{ device_usb_info.disk.dev }} {{ device_usb_block.stdout }}'
    when: '"/usb" in device_usb_block.stdout'

  #
  # Device is supposed to have 2 partitions :
  #  - #1 boot
  #  - #2 rootfs
  # If so :
  #  - resize rootfs to maximum size available
  #  - remove boot

  - block:
    - debug:
        msg: 'Removing boot partition'
    - name: 'Remove partition'
      parted:
        device: '{{ raspian_usb_root_device }}'
        number: '{{ device_usb_info.partitions[0].num }}'
        state: absent
    when: device_usb_info.partitions | length > 1 and device_usb_info.partitions[0].num != 2

  - block:
    - debug:
        msg: 'Resizing rootfs'
    - name: 'Grow partition'
      # Module parted does not grow partitions
      command: 'parted --script {{ raspian_usb_root_device }} resizepart {{ device_usb_info.partitions[-1].num }} 100%'
    - name: 'Grow filesystem'
      filesystem:
        fstype: ext4
        dev: "{{ raspian_usb_root_device }}{{ device_usb_info.partitions[-1].num }}"
        resizefs: yes
    when: device_usb_info.disk.size > device_usb_info.partitions[-1].end

  when: raspian_usb_root_device is defined and raspian_usb_root_device
