---

- name: update {{ raspian_first_boot_pi_user }} user to add ssh authorisez keys
  authorized_key:
    user: "{{ raspian_first_boot_pi_user }}"
    state: present
    key: "{{ lookup('file', raspian_first_boot_pi_pub_key) }}"

- name: update {{ raspian_first_boot_pi_user }} user password
  user:
    name: "{{ raspian_first_boot_pi_user }}"
    password: '{{ raspian_first_boot_pi_password }}'
    update_password: 'always'
  when: raspian_first_boot_pi_password is defined and raspian_first_boot_pi_password | trim | length > 0

- name: update {{ raspian_first_boot_pi_user }} user, add aliases
  copy:
    src: 'bash_aliases'
    dest: "{{ raspian_first_boot_pi_home }}/.bash_aliases"
    owner: "{{ raspian_first_boot_pi_user }}"
    group: "{{ raspian_first_boot_pi_user }}"
    mode: 0644

- name: update useradd skel, add aliases
  copy:
    src: 'bash_aliases'
    dest: '/etc/skel/.bash_aliases'
    owner: 'root'
    group: 'root'
    mode: 0644

- name: update pi user, tune bashrc
  lineinfile:
    path: "{{ raspian_first_boot_pi_home }}/.bashrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    # ensure alias file is sourced
    - regexp: '\[ -f ~/\.bashrc_local \] && source ~/\.bashrc_local'
      line:   '[ -f ~/.bashrc_local ] && source ~/.bashrc_local'
    # tune history
    - regexp: '^HISTFILESIZE=.*$'
      line:    'HISTFILESIZE='
    - regexp: '^HISTSIZE=.*$'
      line:    'HISTSIZE='
    - regexp: '^HISTCONTROL=.*$'
      line:    'HISTCONTROL=ignoreboth:erasedups'
