---


# run commande to activate cam driver
- name: Load the camera driver
  ansible.builtin.command: /usr/bin/sudo /usr/sbin/modprobe bcm2835-v4l2
  when: ansible_facts['os_family'] == 'Debian'

# ensure build required tools are installed
- name: Ensure build tools are installed
  ansible.builtin.package:
    name:
      - build-essential
      - cmake
      - git
    state: present
  when: ansible_facts['os_family'] == 'Debian'

# manual install from git source for the rts stream server
- name: git clone the v4l2rtspserver
  ansible.builtin.git:
    repo: "{{ rts_server_git_repo }}"
    dest: /home/{{ ansible_ssh_user }}/v4l2rtspserver
    version: master
  when: ansible_facts['os_family'] == 'Debian'

# build the rts stream server
- name: Build the v4l2rtspserver
  ansible.builtin.command:
    cmd: >
      /usr/bin/sudo /bin/bash -c 'cd /home/{{ ansible_ssh_user }}/v4l2rtspserver && cmake . && make && make install'
  when: ansible_facts['os_family'] == 'Debian'

# define systemctl service for the rts stream server
- name: Create systemd service for v4l2rtspserver
  ansible.builtin.copy:
    dest: /etc/systemd/system/v4l2rtspserver.service
    content: |
      [Unit]
      Description=RTSP Server for Raspberry Pi Camera
      After=network.target
      [Service]
      ExecStart=/usr/local/bin/v4l2rtspserver -F 30 -W 640 -H 480 -P 8554 /dev/video0
      Restart=always
      [Install]
      WantedBy=multi-user.target

# open ufw port for camera streaming
- name: Open UFW port for camera streaming
  ansible.builtin.ufw:
    rule: allow
    port: 8554
  when: ansible_facts['os_family'] == 'Debian'
