---

- name: APT | Install few packages required by docker compose
  apt:
    pkg:
      - 'build-essential'
      - 'libssl-dev'
      - 'libffi-dev'
      - 'python3-dev'
    state: present
    update_cache: yes
    cache_valid_time: 3600
