---

- block:
    # add ssh (on demand)
    - name: Enable ssh
      copy:
        content: ''
        dest: '{{ raspian_boot_mount_dir }}/ssh'
        force: no
        mode: 0740
      when: raspian_enable_ssh

    # enable wifi (on demand)
    - name: Add wifi configuration
      template:
        dest: '{{ raspian_boot_mount_dir }}/wpa_supplicant.conf'
        src: wpa_supplicant.conf.j2
        mode: 0740
      when: raspian_enable_wifi and raspian_wifi_ssid is defined and raspian_wifi_psk is defined

    # Overlay allow to have a shutdown button without dedicated code
    # https://github.com/pali/raspberrypi-linux/blob/rpi-4.19.y/arch/arm/boot/dts/overlays/README#L879 
    - name: Power on/off simple button
      lineinfile:
        path: '{{ raspian_boot_mount_dir }}/config.txt'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        # Activates overlay
        - regexp: '^dtoverlay=gpio-shutdown$'
          line:    'dtoverlay=gpio-shutdown'
        # Activates led on power on
        - regexp: '^gpio=4=.*$'
          line:    'gpio=4=op,dh'

  when: raspian_boot_mount_dir is defined
